jwt:
  secret: {key}
  accessTokenExpTime: {ms}
  refreshTokenExpTime: {ms}

# 임의로 관리 중인 값 임
host: "http://localhost"
port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true

  security:
    user:
      password: {password}

  webservices:
    path: "/api"

logging:
  level:
    org.hibernate.sql: DEBUG
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace
